name = "Osprey"
license = "GNU3.0"
licenselink = "https://github.com/http://toul.io//osprey/blob/master/LICENSE.md"
description = "Clean, responsive one-page portfolio accompanied by a minimalist blog."
homepage = "https://github.com/http://toul.io//osprey"
tags = ["blog", "portfolio", "gallery", "minimalist", "responsive", "flexbox"]
features = ["blog", "portfolio", "google analytics"]
min_version = 0.24.1

[author]
    name = "Toul Cranmer"
    homepage = "http://toul.io/.com"
